JOB = '/jobs.json'
JOB_V2 = '/jobs'
UPLOAD_JSON = '/jobs/upload.json'
UPLOAD_FILE_TO_JOB = '/jobs/%s/upload.json'
DELETE = '/jobs/%s/hard'
UPDATE = '/jobs/%s.json'
COPY = '/jobs/%s/copy?'
COPY_TEMPLATE = '/jobs/%s/copy.json?'
ROW_COUNT = '/jobs/%s/units/ping.json'
ROWS = '/jobs/%s/units.json?page=1'
UNIT = '/jobs/%s/units/%s.json'
SPLIT_UNITS = '/jobs/%s/units/split?on=%s&with=%s'
ADD_ROW = '/jobs/%s/units.json'
JSON_JOB_STATUS = '/jobs/%s.json'
JOB_STATUS = '/jobs/%s/ping.json'
CONVERT_UPLOADED_TQ = '/jobs/%s/gold.json'
SET_TASK_PAYMENT = '/jobs/%s.json'
LAUNCH_JOB = '/jobs/%s/orders.json'
PAUSE_JOB = '/jobs/%s/pause.json'
RESUME_JOB = '/jobs/%s/resume.json'
CANCEL_JOB = '/jobs/%s/cancel.json'
CANCEL_UNIT = '/jobs/%s/units/%s/cancel.json'
CHANNELS = '/jobs/%s/channels'
DISABLE_CHANNEL = '/jobs/%s/disable_channel'
DELETE_UNIT = '/jobs/%s/units/%s'
UPDATE_UNIT = '/jobs/%s/units/%s.json'
JOB_TAGS = '/jobs/%s/tags'
NOTIFY_CONTRIBUTOR = '/jobs/%s/workers/%s/notify.json'
PAY_CONTRIBUTOR_BONUS = '/jobs/%s/workers/%s/bonus.json'
REJECT_CONTRIBUTOR = '/jobs/%s/workers/%s/reject'
FLAG_CONTRIBUTOR = '/jobs/%s/workers/%s.json'
TEAMS = '/users/teams'
SWITCH_API_TEAM = '/users/switch_api_team/%s'
LEGEND = '/jobs/%s/legend.json'
MAX_CROWD_PAY = '/jobs/%s/max_pay_for_crowd'
GET_BALANCE = '/account.json'
UPLOAD_TAXONOMY = '/jobs/%s/taxonomy?key=%s'
RESTORE_JOB = '/jobs/%s/restore'


URL = "https://api.{}.cf3.us/v1"
URL_V2 = "https://api.{}.cf3.us/v2"
API_BETA_V2 = "https://api-beta.{}.cf3.us/v2"
PROD = "https://api.appen.com/v1"
FED = "https://app.{}.secure.cf3.us/builder/v1"
FED_CUSTOMIZE = "https://{}/builder/v1"
HIPAA = "https://api.nxxgpxhq0rum22cd.staging.cf3.us/v1"
STAGING = "https://api.staging.cf3.us/v1"
STAGING_V2 = "https://api.staging.cf3.us/v2"
INTEGRATION = "https://api.integration.cf3.us/v1"

