#!/usr/bin/env bash

ECR_URL='411719562396.dkr.ecr.us-east-1.amazonaws.com'
IMAGE_NAME='qa-automation'

[ -z "$IMAGE_TAG" ] && IMAGE_TAG=latest
echo "IMAGE_TAG='$IMAGE_TAG'"

echo BUILD $ECR_URL/$IMAGE_NAME:$IMAGE_TAG
docker build -t $ECR_URL/$IMAGE_NAME:$IMAGE_TAG .

echo PUSH TO ECR $ECR_URL/$IMAGE_NAME:$IMAGE_TAG
docker push $ECR_URL/$IMAGE_NAME:$IMAGE_TAG
