// License: Proprietary
// Copyright (c) 2019, Figure Eight Technologies, Inc.
// All rights reserved - Do Not Redistribute

pipeline {
  agent { label 'docker' }

   options{
    ansiColor('xterm')
    disableConcurrentBuilds()
    timeout(time: 50, unit: 'MINUTES')
  }

  environment {
      ECR_URL = "411719562396.dkr.ecr.us-east-1.amazonaws.com"
      IMAGE_REPO = "qa-automation"
      IMAGE_NAME = "qa-automation"
      TAG = "latest"
      GIT_SHA7 = "${GIT_COMMIT[0..6]}"
      TIMESTAMP = "${new Date(currentBuild.startTimeInMillis).format("yyMMddHHmmssSSS")}"
      DATE_SHA_TAG = "$TIMESTAMP-$GIT_SHA7"
      CURRENT_BUILD_IMAGE_NAME = "$IMAGE_REPO:$TAG"
      TIMESTAMPED_IMAGE_NAME = "$IMAGE_REPO:$DATE_SHA_TAG"
      MASTER_IMAGE_NAME = "$IMAGE_REPO:master"
      RANDOM_NUMBER = "${Math.abs(new Random().nextInt() % 1000) +100}"

   }
  stages {
     stage('Start tests') {
         steps {
                echo "Starting docker..."
                sh """
                  set +x
                  \$(aws ecr get-login --no-include-email --region us-east-1)
                  set -xe
                  set +e
                  docker image ls
                  docker ps -a
                  docker run --name  qa-automation-${TIMESTAMP} ${ECR_URL}/qa-automation:${TAG} /srv/jenkins_support/run.sh ${ENV} ${TYPE} ${FLAKY}
                  docker cp qa-automation-${TIMESTAMP}:/srv/result .
                  docker cp qa-automation-${TIMESTAMP}:/srv/allure_report .
                  docker rm -f qa-automation-${TIMESTAMP}
                  docker rmi -f ${ECR_URL}/qa-automation:${TAG}
                  docker image ls
                  ls
                 """
                 publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'result/',
                        reportFiles: 'report.html',
                        reportName: 'Pytest report',
                        includes: '**/*',
                        reportTitles: ''
                ])
                 publishHTML([
                        allowMissing: false,
                        alwaysLinkToLastBuild: true,
                        keepAll: true,
                        reportDir: 'allure_report',
                        reportFiles: 'index.html',
                        reportName: 'Allure report',
                        includes: '**/*',
                        reportTitles: ''
                 ])
                junit 'result/*.xml'
                archiveArtifacts artifacts: 'Failed_scenarios/', allowEmptyArchive: true
          }

     post {
            unstable {
                withCredentials([string(credentialsId: 'slack_token',variable: 'SLACK_TOKEN')]){
                 sh """
                   if [ "$JOB_NAME" = "qa-automation/"$ENV"_api_smoke_tests" ]
                   then
                        curl -s https://slack.com/api/chat.postMessage \
                                            -H "Content-type: application/json" \
                                            -H "Authorization: Bearer $SLACK_TOKEN" \
                                            --data \
                                            '{
                                              "as_user":"false",
                                              "channel":"#${ENV}_api_smoke_test",
                                              "attachments": [{
                                                "text":"${JOB_NAME} ${currentBuild.displayName} failed on ${ENV}",
                                                "title": "API smoke tests report",
                                                "title_link": "${BUILD_URL}testReport/",
                                                "color": "warning"
                                              }]
                                            }'

                   else
                      echo "no slack notification"
                   fi
                    """
                }
            }
     }
  }
}